version: "3"
services:

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi:
    build: .
    container_name: my_fastapi
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_QUEUE: "counts_queue"
